"""Structural read-only view of configuration owned by the control process."""

from pathlib import Path
from typing import Literal, Protocol


class ControlSettingsView(Protocol):
    """Only configuration authority that control-side composition may consume."""

    @property
    def mode(self) -> Literal["mcp", "http", "both", "stdio"]: ...

    @property
    def host(self) -> str: ...

    @property
    def port(self) -> int: ...

    @property
    def state_dir(self) -> Path: ...

    @property
    def data_dir(self) -> Path: ...

    @property
    def base_url(self) -> str | None: ...

    @property
    def resolved_base_url(self) -> str: ...

    @property
    def auth_mode(self) -> Literal["none", "oauth"]: ...

    @property
    def oauth_admin_pin(self) -> str | None: ...

    @property
    def oauth_access_token_ttl_s(self) -> int: ...

    @property
    def mcp_session_idle_timeout_s(self) -> int: ...

    @property
    def mcp_max_sessions(self) -> int: ...

    @property
    def ui_enabled(self) -> bool: ...

    @property
    def ui_path(self) -> str: ...

    @property
    def ui_tui_command(self) -> str | None: ...

    @property
    def ui_terminal_idle_timeout_s(self) -> int: ...

    @property
    def ui_wallpaper(self) -> Literal["aurora", "grid", "none"]: ...

    @property
    def executor_max_pending_commands(self) -> int: ...

    @property
    def executor_pairing_max_pending(self) -> int: ...

    @property
    def executor_pairing_ttl_s(self) -> int: ...

    @property
    def max_agent_sessions(self) -> int: ...

    @property
    def agent_session_retention_s(self) -> int: ...

    @property
    def tool_timeout_s(self) -> float: ...

    @property
    def max_http_request_bytes(self) -> int: ...

    @property
    def max_todos(self) -> int: ...

    @property
    def max_todo_bytes(self) -> int: ...

    @property
    def file_download_enabled(self) -> bool: ...

    @property
    def file_download_default_ttl_s(self) -> int: ...

    @property
    def file_download_max_ttl_s(self) -> int: ...

    @property
    def file_download_default_max_downloads(self) -> int: ...

    @property
    def file_download_max_file_bytes(self) -> int: ...

    @property
    def agent_bridge_enabled(self) -> bool: ...

    @property
    def agent_config_dir(self) -> Path: ...

    @property
    def agent_auth_dir(self) -> Path: ...

    @property
    def agent_mcp_probe_timeout_s(self) -> int: ...

    @property
    def agent_mcp_call_timeout_s(self) -> int: ...

    @property
    def agent_dynamic_mcp_tools(self) -> bool: ...
